create bowling.rb
Shrimprin/ruby-practices pull request #3
Opened 2023-06-20 00:03 UTC by Shrimprin

プラクティス「ボウリングのスコア計算プログラム」の課題提出です。
レビューお願いいたします。

2023-06-25 14:09 UTC, u1tnk requested changes

2023-06-25 14:09 UTC, u1tnk commented on 03.bowling/bowling.rb
> +    total_score = 0 # スコアの合計
total_scoreで 「スコアの合計」なのは自明なのでコメントはしないで大丈夫です。
コメントはプログラムだけではどうしても伝わらない補足を書くようにしましょう。

2023-06-25 14:09 UTC, u1tnk commented on 03.bowling/bowling.rb
> +    (shot_index..@shots.length - 1).each do |i|
ここは Arrayクラスのメソッド一覧などを見てもっと効率的に書けないか考えてみてください 💪

2023-06-27 09:25 UTC, Shrimprin commented
レビューありがとうございます！
コメントをどこまで細かく残すか悩みどころでしたが、ご助言でスッキリしました。
再度ご確認をお願いいたします。

2023-06-27 14:22 UTC, u1tnk approved these changes

2023-06-27 14:24 UTC, u1tnk commented
@Shrimprin 

> コメントをどこまで細かく残すか悩みどころでしたが、ご助言でスッキリしました。

細かいところなので approveしましたが、まだもうちょっとコメント多いのでご注意ください。

例えば  `strike?` などはコメントが無くても分かるはずです。
怪しかったらメソッド名を見直す方を優先しましょう。

2023-07-02 04:25 UTC, merged